"""Public company job boards validated with live remote postings on 2026-09-15.

Board names are configuration, not separate parser implementations. Jobs can close;
the health dashboard records a source failure instead of claiming a dead board works.
"""

BOARDS = (
    ("greenhouse", "datadog", "Datadog"),
    ("greenhouse", "cloudflare", "Cloudflare"),
    ("greenhouse", "databricks", "Databricks"),
    ("greenhouse", "twilio", "Twilio"),
    ("greenhouse", "gusto", "Gusto"),
    ("greenhouse", "gitlab", "GitLab"),
    ("greenhouse", "stripe", "Stripe"),
    ("greenhouse", "coinbase", "Coinbase"),
    ("greenhouse", "airbnb", "Airbnb"),
    ("greenhouse", "discord", "Discord"),
    ("greenhouse", "vercel", "Vercel"),
    ("greenhouse", "pagerduty", "PagerDuty"),
    ("greenhouse", "dropbox", "Dropbox"),
    ("greenhouse", "airtable", "Airtable"),
    ("greenhouse", "fivetran", "Fivetran"),
    ("greenhouse", "launchdarkly", "LaunchDarkly"),
    ("greenhouse", "grafanalabs", "Grafana Labs"),
    ("greenhouse", "reddit", "Reddit"),
    ("greenhouse", "pinterest", "Pinterest"),
    ("greenhouse", "instacart", "Instacart"),
    ("greenhouse", "doordashusa", "DoorDash"),
    ("greenhouse", "mercury", "Mercury"),
    ("greenhouse", "anthropic", "Anthropic"),
    ("greenhouse", "tenableinc", "Tenable"),
    ("greenhouse", "wizinc", "Wiz"),
    ("greenhouse", "chainguard", "Chainguard"),
    ("greenhouse", "abnormalsecurity", "Abnormal Security"),
    ("greenhouse", "expel", "Expel"),
    ("greenhouse", "huntress", "Huntress"),
    ("greenhouse", "axonius", "Axonius"),
    ("greenhouse", "censys", "Censys"),
    ("greenhouse", "bugcrowd", "Bugcrowd"),
    ("greenhouse", "socket", "Socket"),
    ("greenhouse", "bishopfox", "Bishop Fox"),
    ("greenhouse", "praetorian", "Praetorian"),
    ("greenhouse", "remotecom", "Remote"),
    ("greenhouse", "chime", "Chime"),
    ("greenhouse", "canonical", "Canonical"),
    ("ashby", "confluent", "Confluent"),
    ("ashby", "plaid", "Plaid"),
    ("ashby", "snowflake", "Snowflake"),
    ("ashby", "notion", "Notion"),
    ("ashby", "sentry", "Sentry"),
    ("ashby", "ramp", "Ramp"),
    ("ashby", "linear", "Linear"),
    ("ashby", "openai", "OpenAI"),
    ("ashby", "materialsecurity", "Material Security"),
    ("ashby", "hackerone", "HackerOne"),
    ("ashby", "semgrep", "Semgrep"),
)
